name: Automated API tests using Postman CLI

on: 
  push:
  workflow_dispatch:
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login to Postman CLI
        run: postman login --with-api-key "${{ secrets.POSTMAN_API_KEY }}"
        
      # 1. Updated Step: Configured the HTML reporter and set the target output file path
      - name: Run API tests
        run: |
          postman collection run "16527715-24c48c29-43de-45f5-bd8c-a48e489b6327" --reporters cli,html --reporter-html-export report.html

      # 2. New Step: Upload the generated report file to the GitHub Actions overview dashboard
      - name: Upload HTML Test Report Artifact
        if: always() # This ensures the report uploads even if a test case fails
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: report.html

